wg-upgrades/meeting-notes/2019-03-19.md
Add upgrades WG notes from 2019-03-19.
=> chore: upgrades WG notes 2019-03-19

wg-releases/meeting-notes/2019-03-27.md
Add the notes for this evening's releases wg meeting.
=> chore: Add meeting notes for Releases WG

wg-outreach/meeting-notes/2019-04-01.md
=> docs: add 2019-04-01 Outreach WG meeting notes

playbooks/responses/first-warning.md, playbooks/responses/how-it-works.md
=> feat: updates to ban process

wg-releases/meeting-notes/2019-04-04.md
Bit late on this, apologies! Minutes from last week.
=> docs: add release wg minutes from 04-04

wg-outreach/meeting-notes/2019-04-15.md
=> docs: add Outreach WG 2019-04-15 meeting notes

wg-security/membership-and-notifications.md
=> docs: update name of notification group

wg-releases/meeting-notes/2019-04-17.md
=> docs: Add Release WG 2019-04-17 meeting notes

wg-outreach/meeting-notes/2019-04-29.md
=> docs: Outreach WG notes for 2019-04-29

wg-releases/meeting-notes/2019-05-01.md
Add 5/1 wg-releases mtg notes.
=> docs: add 5/1 wg-releases mtg notes

wg-releases/retros/5.0.0.md
=> docs: add retro for 5.0.0

wg-upgrades/README.md
/cc @nornagon @codebytere @electron/wg-upgrades 😄
=> docs: add Ujjwal to Upgrades WG members

wg-releases/meeting-notes/2019-05-08.md
=> chore: add 5/8 release wg notes

wg-community-safety/README.md
=> Add `@lee-dohm` to wg-community-safety member list

wg-website/README.md
@Kilian is stepping up to take my place as the chair of the website working group ✨
=> chore: update website working group chair

wg-releases/meeting-notes/2019-05-30.md
Add Release WG notes from 5/29
=> docs: add Release WG notes from 5/29

wg-community-safety/new-reports-rotation.md
As discussed in our meeting last week, we're going to have a rotation for incoming reports. I used the order we were listed in the WG readme. Let me know if you want me to change anything!
=> docs: C&S WG rotation

wg-releases/README.md
Yay, i'm almost an observer now...
=> docs: Add name to README

wg-releases/README.md
=> docs: Add my name to the releases wg README

wg-docs-tools/meeting-notes/2019-06-06.md
CC: @felixrieseberg @Kilian @ckerr as y'all have action items :smile:
=> feat: add Docs & Tools WG meeting notes for 2019-06-06

wg-releases/meeting-notes/2019-06-12.md
Add Release WG notes from yesterday's meeting.
=> docs: add 6/12 Release Wg meeting notes

wg-releases/meeting-notes/2019-06-19.md
=> docs: add wg-releases notes for 6/19

wg-docs-tools/meeting-notes/2019-07-18.md
=> docs: add Docs & Tools WG meeting notes for 2019-07-18

wg-releases/meeting-notes/2019-07-17.md
=> docs: add Release WG meeting notes for 7/17

wg-website/repos.md
per WG meeting of 2019-07-25 https://github.com/electron/governance/pull/129/files#diff-18b87a53a47693bf4eef2977efa091fc
=> docs: add hubdown to Website WG list of repo's

wg-releases/major-release-process.md
Adding an item for release notes for our major release process prep doc
cc @codebytere
=> docs: add item for major version release prep

wg-releases/meeting-notes/2019-08-07.md, wg-releases/meeting-notes/2019-08-14.md
Adds meeting notes from  8/7/19 & 8/14/19!
=> docs: add Releases notes 8/7 & 8/14

wg-community-safety/leave-policy.md
/cc @electron/wg-community-safety
=> docs: Create maintainer leave of absence policy re: Slack permissions

wg-releases/README.md
Update Release WG list to reflect current members
=> docs: remove inactive members from releases WG

wg-administrative/README.md
Update chair and schedule next admin wg meeting
=> feat: Rotate admin chair

wg-website/README.md
@BinaryMuse, we'll miss you! Thank you so much for everything you've done 🙇
=> docs: Update membership information for `wg-website`

wg-community-safety/meeting-notes/2019-09-05.md
=> docs: Add meeting minutes for 2019-09-05

wg-outreach/README.md
This PR removes old members who no longer attend the working group, and adds four new members (Tierney, Erik, Erick, and myself).
=> Update working group members

wg-docs-tools/meeting-notes/2019-09-26.md
=> feat: add Docs & Tools WG meeting notes for 2019-09-26

wg-administrative/initiatives/OpenJS.md
Form the OJS initiative that can take action. Suggestions welcome.
cc/
@codebytere
@cruzerld
@felix
@groundwater
@jkleinsc
@keegan
@nornagon
@tierney
@mylesborins
This will still need to be ratified by the admin-wg with 👍 from other WGs
Closes #145
=> docs: OpenJS Initiative

wg-outreach/README.md
As discussed in this morning's meeting, I've prepared pretty broad text to specify our membership requirements. Suggestions and change requests welcome!
=> docs: Specify membership requirements for wg-outreach

wg-community-safety/meeting-notes/2019-09-19.md
=> docs: Add Community and Safety WG 2019-09-19 minutes

wg-docs-tools/README.md, wg-outreach/README.md, wg-releases/README.md, wg-security/README.md
Adding OKRs pulled from [post-summit](http://bit.ly/ems-nyc-output) outputs
=> docs: add OKRs for WGs

wg-ecosystem/README.md, wg-upgrades/README.md
Remove nitsakh from upgrades and docs-and-tools working groups
=> chore: Remove nitsakh from the members list

wg-ecosystem/README.md
Does what it says on the tin. Also, alphabetize the member names.
=> Add Erick Zhao to the Ecosystem WG :tada:

wg-ecosystem/meeting-notes/2019-10-10.md
First Ecosystem WG meeting! :tada:
=> docs: Ecosystem WG 2019-10-10 minutes

wg-upgrades/README.md
=> docs: remove ryzokuken from Upgrades WG

.github/CODEOWNERS
* Removed entries for Docs & Tools, Website
* Added entries for Ecosystem, API
=> docs: CODEOWNERS updates

wg-community-safety/meeting-notes/2019-10-03.md
=> docs: Community and Safety WG 2019-10-03 minutes

wg-qa/README.md, wg-releases/wg-qa/README.md, wg-releases/wg-qa/meeting-notes/2019-9-18.md, wg-releases/wg-qa/meeting-notes/2019-9-25.md
=> feat: Create wg-qa initial README.md

wg-upgrades/meeting-notes/2019-10-22.md
=> chore: add upgrades-wg notes 2019-10-22

wg-releases/major-version-release-schedule.md
If this is all 👍 then I'll update our google calendar
=> docs: release schedule for 8.0.0

wg-releases/major-version-release-schedule.md
Adding `Covalence Conf` note for our internal release calendar
=> docs: add covalence conf to release schedule

wg-upgrades/README.md
Add myself to the upgrades working group docs.
=> docs: add @loc as wg-upgrades member

wg-community-safety/README.md
=> docs: Add rules for membership to the Community and Safety WG README

charter/README.md
This PR adds and explicates a few more areas of responsibility for each WG Chair that have been implicit but would be likely better made explicit!
=> docs: add more Chair responsibilities

wg-ecosystem/README.md
As I mentioned in today's Ecosystem WG meeting.
CC: @shiftkey @miniak
=> docs: remove inactive members from Ecosystem WG

wg-ecosystem/meeting-notes/2019-10-31.md
=> docs: Ecosystem WG 2019-10-31 minutes

wg-api/meeting-notes/2019-11-04.md
=> docs: add wg-api notes from 11/4

wg-administrative/README.md
Closes https://github.com/electron/governance/issues/209.
Removes dead link.
=> chore: remove dead link

wg-outreach/meeting-notes/2019-11-25.md
Better late then never, right?
=> docs: wg-outreach 2019-11-25 meeting notes

wg-ecosystem/meeting-notes/2020-01-09.md
=> docs: Ecosystem WG 2020-01-09 minutes

wg-ecosystem/README.md, wg-outreach/README.md
Keeping my governance info updated, I guess!
=> chore: update @erickzhao location

wg-releases/major-version-release-schedule.md
I'll add to our calendar if everything looks good
=> chore: Releases WG 9.0.0 schedule

wg-ecosystem/meeting-notes/2020-02-06.md
=> docs: Ecosystem WG 2020-02-06 minutes

wg-outreach/meeting-notes/2020-02-03.md
Seems like we forgot to add these to GitHub 🙈
=> docs: wg-outreach 2019-02-03 meeting notes

wg-releases/retros/9.0.0-beta.1.md
This is a retro for the delayed release of 9.0.0-beta.1
=> docs: add retro for 9.0.0-beta.1

wg-ecosystem/meeting-notes/2020-02-20.md
=> docs: Ecosystem WG 2020-02-20 minutes

wg-ecosystem/meeting-notes/2020-03-05.md
=> docs: Ecosystem WG 2020-03-05 meeting notes

wg-api/spec-documents/message-ports.md
imported from https://hackmd.io/bwzFRWZzRIyewIBc1Vf7DQ
=> docs: spec document: MessagePorts

wg-api/best-practices.md, wg-api/meeting-notes/2019-10-07.md
This is a rough draft for API Best Practices, nothing here is settled, the purpose of this PR is to collect opinions and get maintainers together to work out a document that most of us agree with.
This document does not mean to be a JavaScript style guide that defines coding styles or naming rules, this means to describe best practices for designing public Electron APIs.
One thing I'm still not sure is to prefer whether getter/setters or properties, as we have discussed in https://github.com/electron/electron/issues/12745 but still have no decision. I have just listed all options here.
Feel free to commit to this branch to fix grammar/wording.
=> docs: draft for API Best Practices

wg-releases/README.md
=> chore: update Chair to @codebytere

wg-releases/meeting-notes/2020-03-25.md
Notes from yesterday's meeting.
=> docs: add 3/25 Releases WG meeting notes

wg-outreach/meeting-notes/2020-03-30.md
=> docs: wg-outreach 2019-03-30 meeting notes

wg-ecosystem/meeting-notes/2020-03-19.md
=> docs: Ecosystem WG 2020-03-19 minutes

wg-releases/major-version-release-schedule.md
I've updated our google calendar with these changes
=> docs: update releases schedule for 9.0 change

wg-ecosystem/meeting-notes/2020-04-02.md
=> docs: Ecosystem WG 2020-04-02 minutes

wg-api/README.md
=> chore: Update chair of API WG

wg-releases/meeting-notes/2020-04-08.md
=> docs: add 2020-04-08 Release WG notes

wg-outreach/README.md
This PR updates the chair in the Outreach WG
=> chore: Update new chair in Outreach WG

wg-releases/meeting-notes/2020-04-15.md
Release notes from today's meeting.
=> docs: add 2020-04-15 release wg notes

wg-administrative/README.md
We generally seek consensus from other WGs. This has been 👍 by admin-wg.
Adding Deani (Slack Inc.) and Anton (Microsoft Developer Division) to Admin WG.
=> chore: Update Admin-WG Members

wg-ecosystem/README.md
=> feat: rotate Ecosystem WG chair to Erick

wg-ecosystem/meeting-notes/2020-04-16.md
=> docs: Ecosystem WG 2020-04-16 minutes

wg-outreach/meeting-notes/2020-05-11.md
Add meeting notes for the Outreach WG for May 11, 2020.
=> docs: Add Outreach WG meeting notes for 2020-05-11

wg-releases/meeting-notes/2020-05-06.md
=> feat: add 2020-05-06 releases notes

wg-releases/meeting-notes/2020-05-13.md
Notes from 2020-05-13.
cc  @electron/wg-releases
=> docs: add 2020-05-13 Release WG notes

wg-ecosystem/meeting-notes/2020-05-14.md
Items to follow up on next meeting:
- @erickzhao: Email Appzi to give feedback about their lack of preferences.
- @erickzhao: Try to figure out better if there's a better meeting time that works for all WG members.
- @felixrieseberg: Look into making the Electron Fiddle experience for switching between major versions more user-friendly.
- @HashimotoYT: Work on prototype for reporting on broken electronjs.org modules.
- @malept: Prepare `electron-forge` 1.0 stable with a note that Native Node Module support with Webpack is not fully supported.
=> docs: Ecosystem WG 2020-05-14 minutes

wg-ecosystem/incidents/2020-05-01.md
Let this be a lesson for the next generation.
✨[Rendered](https://github.com/electron/governance/blob/vh-ecosystem/may-one-incident/wg-ecosystem/incidents/2020-05-01.md) ✨
=> docs(ecosystem-wg): May 1 website incident report

wg-releases/meeting-notes/2020-06-3.md
=> docs: 2020-06-03 release wg notes

wg-ecosystem/meeting-notes/2020-05-28.md
Forgot to upload last meeting's minutes 🙈
=> docs: Ecosystem WG 2020-05-28 minutes

wg-security/README.md
I don't have the bandwidth to properly show up to wg-security, so it's time for me to remove myself. I'm still always happy to help if I can do anything for wg-security!
(Nothing bad happened, I'm just running out of time)
=> chore: Remove @felixrieseberg from wg-security

wg-releases/meeting-notes/2020-06-17.md
=> docs: add 6/17 Releases meeting notes

wg-outreach/meeting-notes/2020-06-22.md
Adds notes for June 22 Outreach WG meeting.
=> Add June 22 Outreach WG meeting notes

wg-releases/wg-qa/README.md
Draft PR until we agree on the new OKRs
=> chore: QA WG's new OKRs

wg-api/meeting-notes/2020-06-15.md, wg-api/meeting-notes/2020-06-29.md, wg-api/meeting-notes/2020-07-13.md
=> chore: add June and July 13 API WG meeting notes

wg-releases/meeting-notes/2020-07-15.md, wg-releases/meeting-notes/2020-07-22.md
Adds some missing release notes for July.
=> docs: release notes for July

wg-releases/meeting-notes/2020-07-29.md
=> chore: add 29/07/2020 Release WG notes

wg-api/README.md
We no longer meet in alternating timezones
=> docs: update API WG meeting time info

wg-ecosystem/README.md
Rotates the WG chair and updates the OKRs
=> docs: update Ecosystem WG README

wg-outreach/README.md, wg-outreach/meeting-notes/2020-08-31.md
Also includes the WG chair rotation in the README.
Action items for next meeting:
@VerteDinde:
* Add auto-moderation to #how-to-get-help channel
* Write how-to-get-help blurb for channel
* Add comment to rules on how to report bad behavior (DM mods or report via Code of Conduct report form)
@erickzhao:
* Set up RSS feed for releases (only stable, and for 3 currently supported versions)
* Create #proj-hacktoberfest-2020 channel
=> docs: add minutes for 08/31 Outreach WG meeting

wg-releases/meeting-notes/2020-09-23.md
=> docs: add 2020-09-23 Release WG notes

wg-releases/meeting-notes/2020-09-30.md
=> docs: add 2020-09-30 Release WG mtg notes

wg-outreach/meeting-notes/2020-10-12.md
=> docs: add Outreach minutes 2020-10-12

wg-releases/meeting-notes/2020-09-09.md, wg-releases/meeting-notes/2020-10-07.md, wg-releases/meeting-notes/2020-10-14.md
Add notes from this week and last.
=> docs: Add Release WG notes 10/7 & 10/14

wg-releases/README.md
Adding my information to the releases wg readme.
=> chore: add @mlaurencin to wg-releases

playbooks/responses/deluge.md
I stole this from @ckerr's response [here](https://github.com/electron/electron/issues/26130#issuecomment-715401207). I like it better than what's here currently.
=> feat: update deluge response with new wording from @ckerr

wg-releases/meeting-notes/2020-10-28.md, wg-releases/meeting-notes/2020-11-04.md
=> docs: add Release WG notes from 2020-11-04

wg-api/README.md
Remove @loc and @VerteDinde and add @zcbenz and @samuelmaddock
=> chore: update API WG members

wg-releases/wg-qa/README.md
@amclegg you are welcome back any time! 😊
=> chore: remove @amclegg from QA WG

wg-upgrades/README.md
also remove @loc from membership
=> chore: update upgrades WG chair to @codebytere

policy/permissions.md
Includes offboarding information around when we delete accounts
=> chore: add GSuite section to permissions policy

policy/joining-governance.md, policy/leaving-governance.md
Taking a first attempt at documenting the steps to add a new governance member and steps for when a member leaves governance. Open to suggestions!
=> chore: document joining/leaving governance steps

wg-upgrades/README.md
=> chore: remove Alexey from Upgrades

wg-security/README.md
per https://github.com/electron/governance/blob/master/policy/observers.md.
=> chore: add @mlaurencin as sec-wg observer

wg-ecosystem/README.md
As per the term outlined previously :) 
Thank you for a successful Google Season of Docs program!
=> docs: remove @bandantonio as Ecosystem observer

wg-outreach/meeting-notes/2021-03-01.md
=> docs: add 2020-03-01 @wg-outreach meeting

wg-releases/meeting-notes/2021-03-03.md
Notes from Releases March 3rd meeting
=> docs: add 2020-03-01 @wg-releases notes

playbooks/responses/repro-steps.md
=> docs: delete repro-steps.md

playbooks/responses/blocked-needs-repro.md
=> docs: the label is called `blocked/need-repro`

wg-ecosystem/meeting-notes/2021-02-18.md, wg-ecosystem/meeting-notes/2021-03-04.md, wg-ecosystem/meeting-notes/2021-03-18.md
Seems like I missed a few meetings 🙇
=> docs: add feb/mar wg-ecosystem meeting notes

wg-releases/README.md
This PR adds @clavin to the releases WG! 🎉
=> docs: add @clavin to releases WG

policy/joining-governance.md
I just realized this is a copy-paste error when I wrote this initially.
=> chore: update Joining Governance doc

wg-releases/meeting-notes/2021-04-07.md
Add 04-07-2021 meeting notes for the Releases WG
=> chore: Add 04-07-2021 meeting notes for the Releases WG

wg-releases/major-version-release-schedule.md
I'll add the milestones to our google calendar also
=> chore: update releases calendar for 14.0.0

wg-upgrades/rotation_generator.js
=> chore: add rotation generator for upgrades

wg-outreach/meeting-notes/2021-07-19.md, wg-outreach/meeting-notes/2021-08-16.md
=> docs: add wg-outreach meeting notes

wg-releases/README.md
=> chore: update Releases chair to @codebytere

wg-administrative/README.md
Admin-wg updates:
Added @molant and @felixrieseberg as reviewers for transparency.
=> feat: Add PlaineKevin to admin-wg

wg-outreach/README.md
Adding my information to the outreach wg readme.
=> chore: add @BlackHole1 to wg-outreach

wg-outreach/README.md
```diff
-     David
-     John-David
+     David
+     Felix
```
_I also alphabetized the list by everyone's GitHub handle._
=> chore: update @wg-outreach members

wg-api/README.md
=> docs: add zoilist as wg-api repo

README.md, wg-api/best-practices.md, wg-api/design-spec-process.md
Two broken links and a missing link.
=> chore: fix some links

wg-api/spec-documents/scroll-view.md
Proposing API changes required for adding a native ScrollView.
Link to the initial feature request: https://github.com/electron/electron/issues/32751
=> docs: scroll-view proposal

playbooks/responses/not-an-issue.md
This accidentally regressed from #463.
=> chore(playbooks): fix Discord link

wg-releases/README.md
Adds Darshan Sen to Releases WG readme
=> chore: add Darshan Sen to Releases WG

wg-ecosystem/README.md, wg-outreach/README.md
Moved from Shanghai to Hangzhou. 📍
=> chore: update blackhole1 region

wg-ecosystem/README.md
This PR adds @georgexu99 to the Ecosystem WG (he was voted in September 2022).
=> feat: add @georgexu99 to Ecosystem WG

.github/CODEOWNERS
Noticed a couple were missing.
=> chore: update CODEOWNERS for working groups

policy/joining-governance.md
=> docs: update onboarding steps

policy/leaving-governance.md
=> chore: update offboarding

README.md
Follow up to https://github.com/electron/governance/pull/508
=> docs: add Infra WG to home

wg-releases/README.md
Copy and paste error slipped in.
=> chore: correct alt text

wg-releases/README.md
=> chore: add @dsanders11 to Releases WG

playbooks/responses/old-version.md
=> chore: fix typo in playbook response

playbooks/issue-triage.md, playbooks/pull-request-triage.md
=> chore: update references from Atom to Electron

policy/slack.md
Detected by the new lint workflow: https://github.com/electron/governance/actions/runs/4928050376/jobs/8805903031#step:8:11
=> chore: fix broken link

wg-ecosystem/README.md
@caoxiemeihao please verify the information!
=> Add @caoxiemeihao to wg-ecosystem

wg-ecosystem/README.md
=> feat: add @erikian to Ecosystem WG

wg-releases/README.md
=> chore: update @mlaurencin's new location

wg-infra/README.md
As in title. See https://github.com/electron/.permissions/pull/207/
=> chore: add @VerteDinde to Infra WG

wg-infra/policy/access/slack.md
=> docs: update Slack workspace primary owner

wg-infra/policy/access/github.md
As voted on and approved by the Administrative Working Group.
=> chore: update GitHub owners

wg-security/README.md
This PR adds @codebytere to the Security WG
=> chore: add @codebytere to the Security WG

wg-ecosystem/README.md, wg-outreach/README.md, wg-releases/README.md
Refs https://github.com/electron/.permissions/pull/216
=> chore: remove other inactive members per policy

wg-infra/scripts/new-npm-package.sh
Script didn't work with npm@10 now it does
=> fix: update wg-infra npm script for npm v10

wg-upgrades/README.md
This PR adds @alicelovescake to the Upgrades WG README
=> chore: add @alicelovescake to Upgrades WG

wg-api/README.md
As discussed in today's meeting.
=> chore(wg-api): remove chair and update async vote description

wg-infra/policy/access/github.md
As discussed @electron/wg-infra
=> chore: solidify owner subset of infra policy

wg-security/ghsa-triage-process.md
As in title.
cc @VerteDinde and @MarshallOfSound
=> doc: initial document for GHSA triage and publish

wg-upgrades/README.md
This happened a while ago but we forgot to update here. 🙂
=> chore: add @samuelmaddock and @dsanders11 to Upgrades WG

wg-administrative/initiatives/OpenJS.md, wg-api/README.md, wg-security/README.md, wg-upgrades/README.md
=> chore: move @nornagon to emeritus

wg-ecosystem/README.md
=> chore: add @mmaietta to Ecosystem WG

wg-outreach/README.md
The docs have an outdated time.
=> docs: update wg-outreach meeting schedule

wg-security/membership-and-notifications.md
=> chore: note confidential nature of need-to-know
