electron/governance

wg-releases/meeting-notes/2019-03-20.md
Adds Meeting Notes from the 3/20/2019 Releases WG meeting.
=> docs(wg notes): add 2019-03-20 Release WG notes

wg-releases/sudowoodo.md
This adds a minimal guide for running and troubleshooting Sudowoodo.
=> docs: add minimal Sudowoodo guide

wg-releases/repos.md
Marks [`electron/cation`](https://github.com/electron/cation) and [`electron/unreleased`](https://github.com/electron/unreleased) as owned by @electron/wg-releases.
=> docs: add (more) assoc repos to release wg

wg-docs-tools/meeting-notes/2019-05-09.md
Add meeting notes for the 2019-05-09 Docs & Tools WG meeting.
=> docs: add 2019-05-09 Docs and Tools WG meeting notes

wg-releases/README.md
Adding new backport rule from output of [Releases WG 5/15 meeting](https://github.com/electron/governance/blob/master/wg-releases/meeting-notes/2019-05-15.md#action-items)
=> docs: new backport rule

wg-docs-tools/README.md
Change the README as per the votes taken in the 2019-06-20 meeting:
* add Brendan as a WG member
* document the previously-implicit requirements for membership
=> docs: update Docs & Tools WG membership info

wg-releases/meeting-notes/2019-06-26.md
=> docs: add WG Releases notes for 6/26

wg-website/emails/request-for-link-on-site.md
This email was recently discussed in the slack chat, documenting it here for future use.
=> docs: default email for requests to be placed on the website

wg-docs-tools/README.md, wg-docs-tools/repos.md
=> docs: move Electron Packager into the Electron org

wg-releases/major-version-release-schedule.md
As discussed in our meeting this week, we are going to move our internal working calendar for major version releases to our directory and the public facing [timeline doc](https://electronjs.org/docs/tutorial/electron-timelines) will just show beta.1 & stable dates to declutter the public page. 
The dates listed in this file will be synced up to the Google calendar that posts into #wg-releases channel.
=> docs: Releases WG major version release schedule

wg-releases/README.md
As per discussion on our last meeting, this PR formally adds the process by which sitting members of the Releases WG may be removed. 
=> docs: enumerate Releases WG removal process

wg-releases/major-release-process.md
Per meeting discussion Wednesday, i've added a preliminary version of a Major Release Prep doc based on some of the tasks outlined [here](https://github.com/electron/electron/projects/20).
Please feel free to comment and leave feedback with any thoughts or things you feel may be missing here!
=> docs: add major release line prep doc

wg-outreach/README.md
Outreach WG chair rotation was done async in #wg-outreach. Outcome is @felixrieseberg will be next Outreach WG chair starting immediately. 
I also added an update for @cruzerld's location.
=> feat: Outreach WG chair rotation

wg-releases/README.md, wg-releases/meeting-notes/2019-08-28.md, wg-releases/meeting-notes/2019-09-04.md
Updates WG chair to @jkleinsc and add missing meeting notes.
=> chore: add missing notes & update readme

wg-docs-tools/README.md
We've rotated the chair in the Slack channel, per our rules.
=> feat: Docs & Tools WG chair rotation, 2019-09

wg-community-safety/leave-policy.md
Similar to https://github.com/electron/governance/pull/138, reduce GitHub organization permissions of Electron governance members on leave
=> docs: Add reduction in GitHub rights to leave policy/process

wg-ecosystem/README.md
Fix Slack channel name and removed an extra word.
=> fix: typos in Ecosystem WG docs

README.md, wg-api/README.md, wg-api/best-practices.md, wg-api/meeting-notes/2019-09-26.md, wg-api/meeting-notes/2019-10-07.md
Does what it says on the tin.
In this PR I've tried to use:
* The mission, as I understood it, that was decided in the first meetings
* The member list from people who signed up in the first meetings
* Membership vote / meeting time boilerplate from wg-upgrades
* Outlined a "Change Procedure" that proritizes unblocking things async to avoid excess meetings / process-for-process'-sake
* Created an agenda section for changes-that-need-unblocking modeled on wg-releases' agenda section for PRs-that-need-backporting
IMO this borrows good practices from other workgroups but I'm not going to claim this is the One True Way. Reviews and suggestions are welcomed!
=> Add API WG

charter/README.md
Our project had an influx of new maintainers after the NYC summit :tada: This is the first time we've had an influx since governance was introduced, and there was room for improvement:
1. Some new volunteers were unsure how to join a Working Group.
1. Some [maintainers](https://github.com/electron/governance/#definitions) were unsure about any process around bringing new volunteers into a Working Group.
1. Most Working Groups don't outline requirements for group membership.
1. C&S's role in overseeing maintainer membership caused some delay in people joining.
This PR tries to address these by:
1. Showing the clear steps a new volunteer can follow to join Slack and/or governance
1. Setting a baseline for participation expectations
1. Placing the C&S notification responsibility on the …
=> feat: explain how new participants can join groups

charter/README.md
Reverts electron/governance#167
This wasn't supposed to land, and did not have approval from admin-wg. An alternative-but-similar proposal was in the works to be posted "soon™"
=> fix: revert "feat: explain how new participants can join groups"

wg-releases/README.md
Updating our BP policy per our meeting on [8/21](https://github.com/electron/governance/blob/master/wg-releases/meeting-notes/2019-08-21.md)
=> docs: update BP policy for betas

wg-api/meeting-notes/2019-10-24.md
Adds notes for today's API WG meeting.
=> docs: add 10/24 API WG notes

wg-releases/RFCs/release-process-change.md
Adds the RFC for the release process change we've since implemented, but whose document was never uploaded. For posterity, we should keep these in the WG folder.
cc @jkleinsc (for doing the work to implement this ✨) @electron/wg-releases
=> docs: add release process change RFC

wg-releases/README.md
This PR explicates some duties that the Chair of the Releases Working Group can expect to perform in order to keep the group running smoothly 🚀 
cc @jkleinsc as current chair :D these are mostly things from my chairship that i don't think i wrote down anywhere
=> docs: explicate Releases Chair duties

wg-api/RFCs/shell-openitem.md
This PR adds the approved RFC for changes to `shell.openItem(item)`.
=> docs: add spec for shell.openItem change

policy/permissions.md
Does what is says on the tin.  This repo is restricted to `gov`
=> chore: add the .permissions repo to the permissions policy

wg-community-safety/slack-access.md
Updates documentation to detail the process of how Multi-Channel / Single-Channel Slack Guests gain access.
=> chore: describe multi and single channel slack guest access

wg-ecosystem/README.md
In the [10/31 :jack_o_lantern: meeting](https://github.com/electron/governance/blob/master/wg-ecosystem/meeting-notes/2019-10-31.md), the Ecosystem WG discussed how to measure the key result "decrease percentage of documented poor-practices". We found that it's difficult to measure differently than the other key result, "increase views on /docs", particularly if the scope is "just our docs". The consensus was to merge the two mentioned KRs together, and this PR is the output item for that.
=> docs: update Ecosystem WG key results

wg-api/meeting-notes/2020-01-13.md
Add meeting notes from yesterday's API WG meeting.
cc @wg-api
=> docs: add meeting notes from 2020-01-13

wg-releases/repos.md
=> chore: add chromedriver to Releases AORs

wg-ecosystem/README.md
This might have been a Daylight Savings thing, but it seems like the UTC time of our meetings is off. We meet at 9:00 AM PT, which is 5:00 PM UTC.
=> docs: fix meeting time for Ecosystem WG

wg-api/README.md
He's been fully inactive for the full length of the WG's existence, which passes the threshold needed to remove someone.
=> docs: remove erikmellum from api wg

wg-api/meeting-notes/2020-02-03.md, wg-api/meeting-notes/2020-03-09.md
=> docs: add missing WG API notes

wg-outreach/README.md
Removing Erik as he has not been active since joining Outreach WG.
=> docs: remove @erikmellum from outreach wg

wg-api/meeting-notes/2020-03-23.md
=> docs: add 2020-03-23 wg-api meeting notes

wg-api/spec-documents/views-api-1-content-view.md
This spec proposes to make parts of `views` related APIs public, which should be enough to implement a simple splash screen for apps.
```js
const {app, nativeImage, webContents, ImageView, TopLevelWindow, WebContentsView} = require('electron')
app.once('ready', () => {
const win = new TopLevelWindow({})
const imageView = new ImageView()
imageView.setImage(__dirname + '/splash.png')
win.setContentView(imageView)
const contents = webContents.create({})
const web = new WebContentsView(contents)
contents.once('did-finish-load', () => win.setContentView(web))
contents.loadURL('https://github.com/')
})
```
=> docs: views API: support setting content view

wg-api/spec-documents/wc-print-sync.md
This PR is a proposal for the following:
`webContents.print()` and `webContents.printToPDF()` should pass identical parameter types in the same shape. Parameters which differ between the two will be changed to remove differences and prevent unwanted bugs. `webContents.print()` will be Promisified.
=> docs: add print API consistency proposal

wg-ecosystem/meeting-notes/2020-04-30.md
Items to follow up on for next meeting:
* @erickzhao will gate Appzi behind English versions of electronjs.org.
* @MarshallOfSound will talk to @zeke about setting up CFA for `hubdown` to move it to GitHub's Product Documentation team.
* @electron/wg-ecosystem will brainstorm potential goals for the near future.
* @MarshallOfSound will remind @samiskin about rebasing electron/electron#19732.
=> docs: Ecosystem WG 2020-04-30 minutes

wg-releases/meeting-notes/2020-04-29.md
There weren't many notes, but I didn't want to just delete them before adding new notes for today's meeting :slightly_smiling_face: 
=> feat: add 2020-04-29 releases notes

wg-outreach/meeting-notes/2020-04-27.md
Adds the notes from the Outreach WG for April 27, 2020
=> docs: Outreach WG April 27, 2020 minutes

wg-security/README.md
Removing myself from the WG member list.
There's no underlying issue here; I just haven't been spending any time on Security WG topics for awhile now, so this change seems appropriate.
CC @electron/wg-security @MarshallOfSound @nornagon
=> chore: remove self from workgroup membership

wg-releases/wg-qa/README.md
Hey @electron/wg-qa, our rules for entry is missing an approval mechanism. To be aligned with other WGs, here's what I suggest. It's similar to other WG's rules.
=> chore: join QA WG approval mechanism

wg-releases/README.md, wg-releases/issue-playbook/already-fixed.md, wg-releases/issue-playbook/duplicate.md, wg-releases/issue-playbook/end-of-life.md, wg-releases/issue-playbook/fill-template.md, wg-releases/issue-playbook/needs-repro.md, wg-releases/issue-playbook/no-response.md, wg-releases/issue-playbook/please-test-newer.md, wg-releases/issue-playbook/wontfix.md, wg-releases/triaging-issues.md
Adds a basic issue triage guide.
=> docs: add issue triage information

playbooks/responses/blocked-needs-repro.md
1. Fix a typo in the "needs repro" message
2. Add a variant that addresses the case when a repro is available but is impractical because it has dependencies that would require us to spelunk a lot of third-party code
=> docs: tweak the needs repro message

wg-releases/meeting-notes/2020-07-29.md, wg-releases/meeting-notes/2020-08-05.md, wg-releases/meeting-notes/2020-08-19.md, wg-releases/meeting-notes/2020-08-26.md, wg-releases/meeting-notes/2020-09-02.md
Adds notes from yesterday's meeting. Also cleans up some formatting from previous meetings.
=> docs: add 9/2 Release WG notes

wg-ecosystem/README.md
In accordance with [the vote we took last week](https://electronhq.slack.com/archives/CNTJBD467/p1599753915028200), this PR adds Anton Zolotukhin to wg-ecosystem.
=> feat(ecosystem): Add Anton Zolotukhin

wg-releases/README.md, wg-releases/feature-backport-requests.md
What it says. Also move feature backport requests to its own file.
=> docs: add WG Release OKRs

wg-outreach/README.md
Back in August, we had a meeting to update our OKRs since we didn't finalize them during the Electron Maintainer Summit. We generated an Objective and a few Initiatives, but never updated our working group's public README.
Here we go, 2 months later!
Miro board, for reference: https://miro.com/app/board/o9J_knuYqMI=/
To review: we also had "Measures" written down on the board. Do we want these to be on the README as well? cc @groundwater @molant 
As a note, we also had an action item to write a blog post about the output from the Summit, but I think that ship has sailed at this point. Maybe next time?
=> chore: update Outreach WG OKRs for 2020

wg-administrative/README.md, wg-ecosystem/README.md, wg-outreach/README.md
With my new role at Slack comes a move at Electron, too -- and I'm joining `wg-admin` to take over the baton from Slack's previous members in that working group.
We've always said that members of `wg-admin` shouldn't have a vote in any of the operative working groups, which I believe is the correct principle to follow. The way I see it, I can still work on `fiddle` and contribute to various outreach projects, I'll just need to follow what those two working groups think. With that in mind, I'm not going anywhere - I'm just swapping out my two voting positions for another one.
(Also, we've discussed that @molant is now the chair of `wg-admin`)
=> chore: Join admin, leave outreach & ecosystem

playbooks/responses/blocked-needs-repro.md, playbooks/responses/end-of-life.md, playbooks/responses/needs-template.md, playbooks/responses/not-an-issue.md
I'm on triage duty this week and some of these responses seemed like they needed a refresh -- e.g. improving phrasing, removing commasplices, or pointing users in the right direction. The only unifying theme across the changes is that they were needed by some of the issues that I triaged :smile_cat: and PRing them separately seemed like overkill.
CC @electron/wg-releases
=> docs: tweak text of issue triage playbook responses

wg-outreach/meeting-notes/2020-10-26.md
Note that @vhashimotoo has decided to withdraw from Electron Governance, but will continue to help with maintaining our Discord server.
Action items:
* @bnb: improve Discord server CTA for verification gate
=> docs: add @wg-outreach meeting minutes 2020-10-26

playbooks/responses/i18n.md
Adds a reusable response for translation errors on `electronjs.org`. These usually pop up either in `electron/electron`, `electron/electronjs.org`, and `electron/i18n`.
cc @molant
=> docs: add i18n playbook

wg-releases/major-version-release-schedule.md
Updating our schedule for 12.0.0. Note that we have 15 weeks until the next stable because of the winter holidays ❄️
=> chore: 12.0.0 schedule

wg-ecosystem/README.md, wg-outreach/README.md
For @electron/wg-outreach and @electron/wg-ecosystem, updated README times to reflect the DST change.
=> docs: update meeting times for DST

policy/permissions.md
Realized we never listed GitHub owners, also updated the repo admin + twitter sections.
=> chore: update permissions.md to more accurately reflect the current state

wg-releases/meeting-notes/2020-11-18.md
Adds notes from today's meeting.
=> docs: add November 18, 2020 Release WG notes

playbooks/issue-triage.md, playbooks/responses/deluge.md
Two small housekeeping changes to the issue triage playbook:
1. `deluge.md` and `not-an-issue.md` have identical responses, so let's merge them.
2. issue-triage.md links to the wrong filename for the EOL response, so fix the link.
=> chore: remove dupe 'deluge' response from playbook

wg-releases/README.md, wg-releases/meeting-notes/2021-04-14.md
This PR updates the Releases WG README to show that @MarshallOfSound is now the Releases Chair (🎉) and adds meeting notes for the April 14 Releases meeting.
=> chore: update Releases WG chair, add 04-14-2021 releases notes

wg-upgrades/README.md
Update @electron/wg-upgrades chair, members, and time zones.
=> chore: update @wg-upgrades members

wg-releases/retros/15.0.0-alpha1.md
Timeline written up and conclusions conveyed from the retro last wednesday
=> docs: add retro for 15.0.0-alpha1

playbooks/responses/blocked-needs-repro.md
We've spent the last cycle getting [Bugbot](https://github.com/electron/bugbot) to be stable enough for general use, and I think we're finally ready to start asking bug reporters to have their testcases call [app.exit(0) for passed test and app.exit(1) for a failed test](https://www.electronjs.org/docs/latest/api/app/#appexitexitcode).
This PR updates the playbook to give issue triagers a copy-paste friendly version of asking for this.
Fixes https://github.com/electron/bugbot/issues/44 .
=> docs: add bugbot to issue triage playbook

playbooks/responses/i18n.md, playbooks/responses/not-an-issue.md
They got updated at the beginning of the year but the playbooks didn't.
=> chore(playbooks): update Electron Discord invite links

README.md, charter/README.md, playbooks/README.md, playbooks/responses/duplicate-notification.md, playbooks/responses/first-warning.md, playbooks/responses/how-it-works.md, playbooks/responses/needs-template.md, policy/joining-governance.md, policy/pull-requests.md, wg-api/best-practices.md, wg-releases/feature-backport-requests.md, wg-releases/issue-playbook/duplicate.md
- Changed links to `electron/electron` to use `main`
- Switched to relative links for within this repo
- Changed links to `electron/electron/blob/master/.github/ISSUE_TEMPLATE` to `electron/electron/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml` since the former no longer exists
=> chore: update links

policy/permissions.md, wg-releases/feature-backport-requests.md, wg-releases/major-release-process.md, wg-releases/sudowoodo.md
Changes lingering references from `master` to `main`.
=> chore: master -> main in docs

charter/README.md, policy/leaving-governance.md, wg-administrative/README.md, wg-api/spec-documents/message-ports.md, wg-api/spec-documents/wc-print-sync.md, wg-releases/major-version-release-schedule.md, wg-releases/sudowoodo.md
Did a full pass of the docs (excluding meeting notes and other historical data) and these were all the typos.
=> chore: fix typos

policy/slack.md
Looks like the last time a per-release channel was created was `9-x-y`, so it's inaccurate to say it's a general practice.
=> chore: Slack channels per release is no longer a general practice

playbooks/responses/blocked-needs-repro.md
Revised based on some of the things that we've discussed this week at the SF hackweek.
CC @electron/wg-releases
=> docs: revise the blocked-needs-repo playlist entry

playbooks/issue-triage.md
A handful of links were broken, mostly due to crossing in-flight with #480.
Also cleaned up the link text in a few cases to make sure it matches to response template names.
We'll get a docs link linter on this repo at some point. 😅
=> chore: fix links in issue triage playbook

wg-api/spec-documents/electron-c-apis.md
This is a proposal for adding C APIs that can be used to interact with internal Electron and Chromium in native modules.
=> docs: Electron C APIs

playbooks/responses/end-of-life.md
this link has moved, so update it here.
=> docs: update supported versions link in end-of-life playbook

wg-ecosystem/README.md, wg-outreach/README.md, wg-releases/README.md, wg-security/README.md
As discussed at the 2022 summit, these "current" OKRs are out of date and not serving any purpose.
=> chore: remove old OKRs from WGs

wg-infra/README.md
As discussed at Summit, this lays the groundwork for a new place for docs, policies and a new organizational structure around the things this working group will own that were previously "unowned"
=> docs: add wg-infra readme

wg-administrative/README.md
As requested at the summit, made some updates to bring the AWG readme up to date with the current state. Notably, I removed the note about the two additional members (the governance rep and the community rep) as well as added a bit more color to our responsibilities. Let me know if it's still too vague or if you have any concerns or additions.
=> docs: update AWG readme

wg-infra/scripts/README.md, wg-infra/scripts/new-npm-package.sh
As in title, adds a new helper script for the infrastructure working group for making or claiming a new npm package for use with CFA.
Once this and https://github.com/continuousauth/web/pull/45 land I can write a new doc on how to set up CFA that will be **substantially** simpler than the original process courtesy of that PR and this helpful script.
=> feat: add new-npm-package script to wg-infra

wg-ecosystem/repos.md
=> chore: Ecosystem WG owns `fiddle-core` repo

charter/README.md, charter/rotating-chair-model.md
This PR sets out to update the charter with the goal of improving its **Accuracy** in regards to how governance has been working in practice. Major changes are as follows:
* The Rotating Chair Model was refactored out (but not changed significantly) to allow working groups to choose their own model of accomplishing work.
* This is supported by working groups where the purpose of a chair wasn't providing value.
* One modification made to the Rotating Chair Model was the ability for a working group to decide its own term length for the chair.
* The concept of a *Delegate* was added to fulfill the governance-related roles that were previously expected by the chair, which not every working group may now have.
* Minor fix-ups to links and comments were made.
Let me know if anything else should …
=> refactor: charter updates - accuracy

wg-ecosystem/repos.md
Repo got renamed so keeping this list up-to-date.
=> chore: rename website repo

wg-ecosystem/repos.md
=> chore: remove archived electron-docs-linter repo

wg-ecosystem/README.md
Cleans up the Ecsoystem WG README to be more accurate to the current state. There's duplicate between the repo list in README and `repos.md` but for the moment I'm going to leave it and will discuss at the next meeting how to clean it up.
=> chore: update Ecosystem WG README

wg-administrative/README.md
This PR updates the Microsoft representative for the Admin Working Group and also contains one key policy change:
* Admin WG members can participate in other working groups, but cannot chair those groups.
Due to this policy change this PR requires approval from all of the current working groups: @electron/wg-api @electron/wg-community-safety @electron/wg-ecosystem @electron/wg-infra @electron/wg-outreach @electron/wg-releases @electron/wg-security @electron/wg-upgrades
=> chore: update Admin WG policy and member

wg-security/README.md
As in title. Emails have also been sent to notify them.
=> chore: remove inactive WG Security members per policy

charter/README.md, wg-administrative/README.md, wg-api/README.md, wg-community-safety/README.md, wg-ecosystem/README.md, wg-outreach/README.md, wg-releases/README.md, wg-security/README.md, wg-upgrades/README.md
This PR follows up on several off boarding items discussed at the October Boston Electron Summit:
- Adds a status for emeritus, or former members of working groups.
- Adds a description for what qualifies a member for emeritus status
- Explicitly defines a process for removing inactive maintainers from working groups.
This PR does not define what an inactive member means - that definition should be determined individually by each working group, and added to individual working group READMEs.
_Note: The members listed here as emeritus were pulled from git and Slack history, and may not be a complete list. If you feel you've been added in error, or are not on the list and should be, please reach out or comment here. 🙏_
=> chore: add emeritus members to working groups

.github/workflows/lint.yml
Fixing the breaking change from `@electron/lint-roller` v2, since this workflow wasn't pinning to a particular version.
Also fixes usage of the boolean input for fetch external links, it was previously always running since `github.event.inputs.fetch-external-links` converts the boolean to a string, but `inputs.fetch-external-links` does not.
=> ci: fix lint workflow

wg-api/README.md
- remove mentions of regular meetings
- update my city 🙂 
- note responsibilities for reviewing PRs and RFCs
- this section was written before we had api labels and the RFCs repo
- list RFCs repo
=> chore: update API WG readme

wg-infra/policy/access/npm.md
This doc has been "an ideal state" for a while and it's close to what we have but not exact so let's fix it.
=> docs: document the current state of npm access

wg-api/README.md, wg-api/best-practices.md
=> docs: type definition changes are not breaking

wg-api/best-practices.md
A few of Electron's existing APIs don't do a good job of supporting extensibility for third-party libraries. Let's try to define best practices to guide future API designs with third-party extensibility in mind.
- Replaces all schemes without an option of appending
- Known issue for third-party libraries https://github.com/electron/electron/issues/40362
- Requires monkey patching to workaround ([see Sentry's example](https://github.com/electron/electron/issues/40362#issuecomment-2248468360))
- Requires replacing all preloads rather than adding a single preload
```js
session.setPreloads([
...session.getPreloads(),
path.join(__dirname, 'new-preload-script.js')
])
```
=> docs: define practices for third-party extensible APIs

wg-releases/release-captain-overview.md
Reasoning:
- We closed the v35 project board and opened the v37 board without reviewing the remaining issues from the v35 board in the WG releases meeting.
- A bunch of new issues were added within the last week. Those should be reviewed to make sure every issue is looked at.
- It's better to have the new release captain do this than the old one.
- Once your release is out, you might not care about it as much anymore as the person whose release cycle just started.
=> docs: add release captain task to copy issues to new board

wg-api/best-practices.md
Adding a style rule to return `null` in APIs where a lookup has no result.
Ref: https://github.com/electron/electron/pull/47850
=> docs: APIs should return null
